---
title: Modelos
subtitle: "Evaluación exploratoria de merluza del pacífico"
description: "Estructura y supuestos de los modelos"
date: "Octubre, 2024"
---

```{r setup, echo=FALSE, include=FALSE}
library(readr)
library(tidyverse)
library(gtsummary)
```

## Introducción

Esta sección presenta el estado del recurso de la merluza del Pacífico (*Merluccius productus*) en el Golfo de
California. La evaluación de la merluza se basa principalmente en los desembarques pesqueros (2000-2023), los
índices de biomasa desde cruceros de área barrida y Captura por Unidad de Esfuerzo (CPUE), como también, las
composiciones de tamaños de la captura comercial y descartada. Los datos de composición por tamaños de la
pesquería agregadas por genero (`hembras + machos`) proporcionan información que facilita la estimación de la
fuerza relativa de las cohortes.

## Enfoque de análisis

El análisis emplea un enfoque de estimación bayesiana para evaluar las posibles consecuencias de la
incertidumbre en parámetros, modelos estructurales alternativos y rendimiento histórico del modelo de
evaluación. Este enfoque combina conocimiento previo sobre mortalidad natural, pendiente de reclutamiento y
otros parámetros con verosimilitudes de índices de biomasa de cruceros de área barrida y datos de composición
de tamaños. La integración de la distribución posterior conjunta sobre los parámetros del modelo a través del
algoritmo de Monte Carlo de cadena de Markov (MCMC) ofrece inferencias probabilísticas sobre parámetros de
modelo inciertos y pronósticos derivados de los mismos.

Los modelos estructurales alternativos se emplean para identificar hipótesis sobre la dinámica de las capturas
descartadas. Estos modelos son evaluados mediante simulaciones que ofrecen datos sobre cómo las diversas
combinaciones de selectividad de pesca para la captura comercial y descartada influirán en los resultados de
gestión, considerando la aplicación repetida de estos procedimientos a largo plazo.

Los análisis fueron realizados en la plataforma [Automatic Differentiation Model
Builder](https://www.admb-project.org/developers/core-team.html) (ADMB) que permite resolver problemas de
optimización no lineal [@Fournier2012]. ADMB es un marco de programación basado en diferenciación automática,
diseñado para modelos altamente no lineales con un gran número de parámetros. Los beneficios de usar ADMB son
eficiencia computacional y alta precisión numérica, ambos cruciales en la evalñuación de la merluza del
pacífico.
